from .Aspecto import Aspecto
from .AuditadoPlan import AuditadoPlan
from .Auditoria import Auditoria
from .AuditoriaXLista import AuditoriaXLista
from .Compromiso import Compromiso
from .Debilidad import Debilidad
from .Documento import Documento
from .Fortaleza import Fortaleza
from .Itinerario import Itinerario
from .ListaVerificacion import ListaVerificacion
from .Oportunidad import Oportunidad
from .PersonalAuditor import PersonalAuditor
from .Plan import Plan
from .Proposito import Proposito
from .Reunion import Reunion
from .Sector import Sector
from .Trabajador import Trabajador